function PlayerRoster () {
  this.players = [];
}

function Player(name, score, myTurn) {
  this.name = name;
  this.score = score;
  this.myTurn = myTurn;
  this.isComputer = false;
}

function ComputerPlayer(name, score, myTurn){
  this.name = name;
  this.score = score;
  this.myTurn = myTurn;
  this.isComputer = true;
}


PlayerRoster.prototype.addPlayer = function(playerToAdd){
  this.players.push(playerToAdd);
}

//variables to be scopred later//
var currentRoster = new PlayerRoster ();

var currentTurnID = 0;

var imageArray = ["one.svg", "two.svg", "three.svg", "four.svg", "five.svg", "six.svg"];





console.log(currentRoster);

function turnSwap () {
      if (currentTurnID < currentRoster.players.length -1) {
        currentRoster.players[currentTurnID].myTurn = false;
        currentRoster.players[currentTurnID + 1].myTurn = true;
        currentTurnID ++
        turnView()
        console.log(currentRoster.players);
      } else if (currentTurnID === currentRoster.players.length -1) {
        currentRoster.players[currentTurnID].myTurn = false;
        currentRoster.players[0].myTurn = true;
        currentTurnID = 0;
        turnView()
        console.log(currentRoster.players);
      } else {
        console.log('you skipped the step');
        console.log(currentRoster.players);
        console.log('currentTurnID is ' + currentTurnID);
        console.log('current roster length ' + (currentRoster.players.length -1));
      };

    // for (i=0; i < currentRoster.players.length; i++) {
    // THIS LOOP WORKS until it hits the last player
    // if (currentRoster.players[i].myTurn === true) {
    //   currentRoster.players[i].myTurn = false;
    //   if (currentRoster.players[i] === currentRoster.players[currentRoster.players.length - 1]) {
    //     currentRoster.players[0].myTurn = true;
    //     i = currentRoster.players.length;
    //   }else{
    //   currentRoster.players[i + 1].myTurn = true;
    //   i = currentRoster.players.length;
    //   console.log(currentRoster.players);
    //   }
    // }
  //}

};// closing turnSwap


var roundScore = 0;
var totalScore = 0;
var totalPlayers = 0;
var roundCount = 0;
var gameTurn = 0;
//

function diceRoll () {
  var twoDice = [];
  for (i = 0; i < 2; i++){
    var dieRoll = Math.floor((Math.random() * 6) + 1);
    twoDice.push(dieRoll);
  }

  return twoDice;
}


function endTurn(){
  totalScore += roundScore;
  currentRoster.players[currentTurnID].score += roundScore;
  printScores();


  console.log("Round Score: " + roundScore);
  console.log(" Total Score for player " + currentTurnID + ":" + currentRoster.players[currentTurnID].score);
  roundScore = 0;
  $(".round-score").text(roundScore);
  if (currentRoster.players[currentTurnID].score >= 100) {
    console.log('You win!');
    pigWinner();
  }

  turnSwap()
}

  function diceRollRound(){
    $(".sorry-message").text("");
    var diceRollResult = diceRoll();
    printDiceValues(diceRollResult);
    console.log("Numbers generated by roll: " + diceRollResult);
    if (diceRollResult[0] === 1 || diceRollResult[1] === 1) {
        // fail condition
        roundScore = 0;
        $(".sorry-message").text("Sorry! You Lose! Next player:");
        $(".round-score").text(roundScore);
        endTurn();
    } else {
      roundScore += diceRollResult[0] + diceRollResult[1]
      console.log(roundScore);
      $(".round-score").text(roundScore);
    }
  }




  ///////////////// UI LOGIC

  var imageArray = ["one.svg", "two.svg", "three.svg", "four.svg", "five.svg", "six.svg"];

  function addPlayerCard() {
  $('.players-container').append('<div class="player-card player-' + (totalPlayers+1) + '"><p class="">' + currentRoster.players[totalPlayers].name + '&nbsp;score:&nbsp;<span class="score">0</span></p></div>')
  totalPlayers ++;
};

function printScores() {
  $('.player-' + (currentTurnID + 1) + ' .score').text(currentRoster.players[currentTurnID].score);
}

function turnView(){
  console.log(currentTurnID);
  $(".player-" + currentTurnID + " p").removeClass('player-turn');
  $(".player-" + (currentTurnID + 1) + " p").addClass('player-turn');
  $(".current-turn-player").text(currentTurnID + 1);
}

function printDiceValues (diceRollResult){
  $(".die1 img").removeClass("hidden").attr('src', 'img/' + imageArray[diceRollResult[0] - 1]);
  $(".die2 img").removeClass("hidden").attr('src', 'img/' + imageArray[diceRollResult[1] - 1]);
}

function pigWinner() {
  $(".player-winner").text(currentRoster.players[currentTurnID].name);
  // $(".player-winner").text(currentRoster.players[currentTurnID].name);
  $(".battle-pigs-main").hide();
  $(".battle-pigs-win").show();
}

/////////////////// BUTTONS AND EVENT TRIGGERS

  $(document).ready(function(){


    $(".start-game").click(function(){
      $(".battle-pigs-addplayer").hide();
      $(".battle-pigs-main").show();
      turnView();
      currentRoster.players[0].myTurn = true;
    })

    $(".add-player-button").click(function(){
      var inputPlayer = new Player ($(".input-player-name").val(), 0, false);
      currentRoster.addPlayer(inputPlayer);
      addPlayerCard();
      console.log("Added new player to roster:" + $(".input-player-name").val());
      console.log(currentRoster);
    })

    $(".add-computer-button").click(function(){
      console.log("01010101");
      var newComputer = new ComputerPlayer ($(".input-player-name").val(), 0, false);
      if(newComputer.name === ""){
        newComputer.name = "Computer";
      }
      currentRoster.addPlayer(newComputer);
      addPlayerCard();
      console.log(currentRoster);
    })

    $('.roll-button').click(function() {
      diceRollRound();
    });
    $('.hold-button').click(function() {
      endTurn();
    });



  });
