function PlayerRoster () {
  this.players = [];
}

function Player(name, score, myTurn) {
  this.name = name
  this.score = score;
  this.myTurn = myTurn;
}

PlayerRoster.prototype.addPlayer = function(playerToAdd){
  this.players.push(playerToAdd);
}

//variables to be scopred later//
var playerOne = new Player ('player person', 0, true);
var playerTwo = new Player ('player girl', 0, false);
var playerThree = new Player ('player man', 0, false);
var playerFour = new Player ('player dog', 0, false);
var playerFive = new Player ('player boy', 0, false);
var currentRoster = new PlayerRoster ();

var currentTurnID = 0;

var myArray = [playerOne, playerTwo, playerThree];
console.log(myArray[myArray.length-1]);

// this is a method running to add Player One to the roster
currentRoster.addPlayer(playerOne);
currentRoster.addPlayer(playerTwo);



console.log(currentRoster);

function turnSwap () {
      if (currentTurnID < currentRoster.players.length -1) {
        currentRoster.players[currentTurnID].myTurn = false;
        currentRoster.players[currentTurnID + 1].myTurn = true;
        currentTurnID ++
        console.log(currentRoster.players);
      } else if (currentTurnID === currentRoster.players.length -1) {
        currentRoster.players[currentTurnID].myTurn = false;
        currentRoster.players[0].myTurn = true;
        currentTurnID = 0;
        console.log(currentRoster.players);
      } else {
        console.log('you skipped the step');
        console.log(currentRoster.players);
        console.log('currentTurnID is ' + currentTurnID);
        console.log('current roster length ' + (currentRoster.players.length -1));
      };

    // for (i=0; i < currentRoster.players.length; i++) {
    // THIS LOOP WORKS until it hits the last player
    // if (currentRoster.players[i].myTurn === true) {
    //   currentRoster.players[i].myTurn = false;
    //   if (currentRoster.players[i] === currentRoster.players[currentRoster.players.length - 1]) {
    //     currentRoster.players[0].myTurn = true;
    //     i = currentRoster.players.length;
    //   }else{
    //   currentRoster.players[i + 1].myTurn = true;
    //   i = currentRoster.players.length;
    //   console.log(currentRoster.players);
    //   }
    // }
  //}

};// closing turnSwap


var roundScore = 0;
var totalScore = 0;
//

function diceRoll () {
  var twoDice = [];
  for (i = 0; i < 2; i++){
    var dieRoll = Math.floor((Math.random() * 6) + 1);
    twoDice.push(dieRoll);
  }

  return twoDice;
}

function endTurn(){
  totalScore += roundScore;
  currentRoster.players[currentTurnID].score += roundScore;
  console.log("Your turn has ended.");
  console.log("Round Score: " + roundScore);
  console.log(" Total Score for player " + currentTurnID + ":" + currentRoster.players[currentTurnID].score);
  roundScore = 0;
  if (totalScore >= 100) {
    console.log('You win!');
  }
  turnSwap()
}

  function diceRollRound(){
    var diceRollResult = diceRoll();
    console.log("Numbers generated by roll: " + diceRollResult);
    if (diceRollResult[0] === 1 || diceRollResult[1] === 1) {
        // fail condition
        roundScore = 0;
        endTurn();
    } else {
      roundScore += diceRollResult[0] + diceRollResult[1]
      console.log(roundScore);
    }
  }



$(document).ready(function(){
  console.log("jquery what upppp");

  $('.roll-button').click(function() {
    diceRollRound();
  });
  $('.hold-button').click(function() {
    endTurn();
  });


});
