function PlayerRoster () {
  this.players = [];
}

function Player(name, score, myTurn) {
  this.name = name
  this.score = score;
  this.myTurn = myTurn;
}

PlayerRoster.prototype.addPlayer = function(playerToAdd){
  this.players.push(playerToAdd);
}

//variables to be scopred later//
var playerOne = new Player ('player person', 0, true);
var playerTwo = new Player ('player girl', 0, false);
var playerThree = new Player ('player man', 0, false);
var playerFour = new Player ('player dog', 0, false);
var playerFive = new Player ('player boy', 0, false);
var currentRoster = new PlayerRoster ();

var currentTurnID = 0;

var imageArray = ["one.svg", "two.svg", "three.svg", "four.svg", "five.svg", "six.svg"];

// this is a method running to add Player One to the roster
currentRoster.addPlayer(playerOne);
currentRoster.addPlayer(playerTwo);



console.log(currentRoster);

function turnSwap () {
      if (currentTurnID < currentRoster.players.length -1) {
        currentRoster.players[currentTurnID].myTurn = false;
        currentRoster.players[currentTurnID + 1].myTurn = true;
        currentTurnID ++
        turnView()
        console.log(currentRoster.players);
      } else if (currentTurnID === currentRoster.players.length -1) {
        currentRoster.players[currentTurnID].myTurn = false;
        currentRoster.players[0].myTurn = true;
        currentTurnID = 0;
        turnView()
        console.log(currentRoster.players);
      } else {
        console.log('you skipped the step');
        console.log(currentRoster.players);
        console.log('currentTurnID is ' + currentTurnID);
        console.log('current roster length ' + (currentRoster.players.length -1));
      };

    // for (i=0; i < currentRoster.players.length; i++) {
    // THIS LOOP WORKS until it hits the last player
    // if (currentRoster.players[i].myTurn === true) {
    //   currentRoster.players[i].myTurn = false;
    //   if (currentRoster.players[i] === currentRoster.players[currentRoster.players.length - 1]) {
    //     currentRoster.players[0].myTurn = true;
    //     i = currentRoster.players.length;
    //   }else{
    //   currentRoster.players[i + 1].myTurn = true;
    //   i = currentRoster.players.length;
    //   console.log(currentRoster.players);
    //   }
    // }
  //}

};// closing turnSwap


var roundScore = 0;
var totalScore = 0;
//

function diceRoll () {
  var twoDice = [];
  for (i = 0; i < 2; i++){
    var dieRoll = Math.floor((Math.random() * 6) + 1);
    twoDice.push(dieRoll);
  }

  return twoDice;
}

function printScores() {
  $('.player-' + (currentTurnID + 1) + ' .score').text(currentRoster.players[currentTurnID].score);
}

function turnView(){
  $(".current-turn-player").text(currentTurnID + 1);
}

function printDiceValues (diceRollResult){
  $(".die1 img").removeClass("hidden").attr('src', 'img/' + imageArray[diceRollResult[0] - 1]);
  $(".die2 img").removeClass("hidden").attr('src', 'img/' + imageArray[diceRollResult[1] - 1]);
}

function endTurn(){
  totalScore += roundScore;
  currentRoster.players[currentTurnID].score += roundScore;
  printScores();


  console.log("Round Score: " + roundScore);
  console.log(" Total Score for player " + currentTurnID + ":" + currentRoster.players[currentTurnID].score);
  roundScore = 0;
  $(".round-score").text(roundScore);
  if (currentRoster.players[currentTurnID].score >= 100) {
    console.log('You win!');
    alert('Player' + (currentTurnID + 1) + ' WINS!!!')
  }

  turnSwap()
}

  function diceRollRound(){
    $(".sorry-message").text("");
    var diceRollResult = diceRoll();
    printDiceValues(diceRollResult);
    console.log("Numbers generated by roll: " + diceRollResult);
    if (diceRollResult[0] === 1 || diceRollResult[1] === 1) {
        // fail condition
        roundScore = 0;
        $(".sorry-message").text("Sorry! You Lose! Next player:");
        $(".round-score").text(roundScore);
        endTurn();
    } else {
      roundScore += diceRollResult[0] + diceRollResult[1]
      console.log(roundScore);
      $(".round-score").text(roundScore);
    }
  }



$(document).ready(function(){

  $('.roll-button').click(function() {
    diceRollRound();
  });
  $('.hold-button').click(function() {
    endTurn();
  });


});
